version: '3.7'

services:
  api-server:
    image: bhhshop-api:latest
    labels:
      - traefik.http.routers.api-server.rule=Host(`bhhshop.bembel.dev`)
      - "traefik.http.routers.api-server.tls.certResolver=default"
      - "traefik.http.routers.api-server.tls=true"

  traefik:
    image: traefik:v2.9
    command: --providers.docker --api.insecure=true
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./static.yml:/etc/traefik/traefik.yml
      - ./dynamic.yml:/etc/traefik/dynamic/dynamic.yml
      - ./acme.json:/etc/traefik/acme/acme.json

  web2:
    image: containous/whoami
    labels:
      - traefik.http.routers.web2.rule=Host(`api.bhhshop.bembel.dev`) || ( Host(`bhhshop.bembel.dev`) && PathPrefix(`/web2`) )
      - "traefik.http.routers.web2.tls.certResolver=default"
      - "traefik.http.routers.web2.tls=true"
