version: '3.7'

services:
  traefik:
    image: traefik:v2.9
    command: --providers.docker --api.insecure=true
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
  web2:
    image: containous/whoami
    labels:
      -  traefik.http.routers.web2.rule=Host(`web2.pirouter.local`) || ( Host(`pirouter.local`) && PathPrefix(`/web2`) )
